package shell

import prompt "github.com/c-bata/go-prompt"

type KeyBind struct {
	Key  prompt.Key
	Fn   prompt.KeyBindFunc
	Desc string
}

var (
	KeyNames = map[prompt.Key]string{
		prompt.ControlA:           "Ctrl + A",
		prompt.ControlB:           "Ctrl + B",
		prompt.ControlC:           "Ctrl + C",
		prompt.ControlD:           "Ctrl + D",
		prompt.ControlE:           "Ctrl + E",
		prompt.ControlF:           "Ctrl + F",
		prompt.ControlG:           "Ctrl + G",
		prompt.ControlH:           "Ctrl + H",
		prompt.ControlI:           "Ctrl + I",
		prompt.ControlJ:           "Ctrl + J",
		prompt.ControlK:           "Ctrl + K",
		prompt.ControlL:           "Ctrl + L",
		prompt.ControlM:           "Ctrl + M",
		prompt.ControlN:           "Ctrl + N",
		prompt.ControlO:           "Ctrl + O",
		prompt.ControlP:           "Ctrl + P",
		prompt.ControlQ:           "Ctrl + Q",
		prompt.ControlR:           "Ctrl + R",
		prompt.ControlS:           "Ctrl + S",
		prompt.ControlT:           "Ctrl + T",
		prompt.ControlU:           "Ctrl + U",
		prompt.ControlV:           "Ctrl + V",
		prompt.ControlW:           "Ctrl + W",
		prompt.ControlX:           "Ctrl + X",
		prompt.ControlY:           "Ctrl + Y",
		prompt.ControlZ:           "Ctrl + Z",
		prompt.ControlSpace:       "Ctrl + Space",
		prompt.ControlBackslash:   "Ctrl + \\",
		prompt.ControlSquareClose: "Ctrl + ]",
		prompt.ControlCircumflex:  "Ctrl + ^",
		prompt.ControlUnderscore:  "Ctrl + _",
		prompt.ControlLeft:        "Ctrl + Left",
		prompt.ControlRight:       "Ctrl + Right",
		prompt.ControlUp:          "Ctrl + Up",
		prompt.ControlDown:        "Ctrl + Down",
		prompt.ControlDelete:      "Ctrl + Del",
		prompt.Up:                 "Up",
		prompt.Down:               "Down",
		prompt.Right:              "Right",
		prompt.Left:               "Left",
		prompt.ShiftUp:            "Shift + Up",
		prompt.ShiftDown:          "Shift + Down",
		prompt.ShiftRight:         "Shift + Right",
		prompt.ShiftLeft:          "Shift + Left",
		prompt.ShiftDelete:        "Shift + Del",
		prompt.Home:               "Home",
		prompt.End:                "End",
		prompt.Delete:             "Del",
		prompt.PageUp:             "PageUp",
		prompt.PageDown:           "PageDown",
		prompt.BackTab:            "BackTab",
		prompt.Insert:             "Ins",
		prompt.Backspace:          "Backspace",
		prompt.Tab:                "Tab",
		prompt.Enter:              "Enter",
		prompt.F1:                 "F1",
		prompt.F2:                 "F2",
		prompt.F3:                 "F3",
		prompt.F4:                 "F4",
		prompt.F5:                 "F5",
		prompt.F6:                 "F6",
		prompt.F7:                 "F7",
		prompt.F8:                 "F8",
		prompt.F9:                 "F9",
		prompt.F10:                "F10",
		prompt.F11:                "F11",
		prompt.F12:                "F12",
		prompt.F13:                "F13",
		prompt.F14:                "F14",
		prompt.F15:                "F15",
		prompt.F16:                "F16",
		prompt.F17:                "F17",
		prompt.F18:                "F18",
		prompt.F19:                "F19",
		prompt.F20:                "F20",
		prompt.F21:                "F21",
		prompt.F22:                "F22",
		prompt.F23:                "F23",
		prompt.F24:                "F24",
		prompt.Any:                "Any",
	}
)
